CREATE TABLE IF NOT EXISTS genre (
  genre_id INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(20) NOT NULL
);


CREATE TABLE IF NOT EXISTS mpa (
  mpa_id INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  user_id INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(40),
  login varchar(20) NOT NULL CHECK (TRIM(login) <> ''),
  email varchar(40) NOT NULL CHECK (TRIM(email) <> ''),
  birthday date
);

CREATE TABLE IF NOT EXISTS films (
  film_id INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(40) NOT NULL CHECK (TRIM(name) <> ''),
  description varchar(200) CHECK(LENGTH(description) > 0 and LENGTH(description) < 201),
  mpa_id INTEGER REFERENCES mpa ON DELETE SET NULL,
  release_date date NOT NULL,
  duration integer CHECK (duration > 0)
);

CREATE TABLE IF NOT EXISTS friends (
  user_id INTEGER REFERENCES users ON DELETE CASCADE,
  friend_id INTEGER REFERENCES users ON DELETE CASCADE,
  confirmed boolean DEFAULT 'false'
 );

 CREATE TABLE IF NOT EXISTS likes (
   user_id INTEGER REFERENCES users ON DELETE CASCADE,
   film_id INTEGER REFERENCES films ON DELETE CASCADE
  );

 CREATE TABLE IF NOT EXISTS films_genre (
   film_id INTEGER REFERENCES films ON DELETE CASCADE,
   genre_id  INTEGER REFERENCES genre ON DELETE CASCADE
  );

  CREATE TABLE IF NOT EXISTS directors (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(255) NOT NULL
  );

  CREATE TABLE IF NOT EXISTS film_directors (
      film_id BIGINT REFERENCES films(film_id) ON DELETE CASCADE,
      director_id BIGINT REFERENCES directors(id) ON DELETE CASCADE,
      PRIMARY KEY (film_id, director_id)
  );